# File .chipperci.yml, which goes in the root of your repository
version: 1

environment:
  php: 8.2
  node: 14
  mariadb: 10.3

services:
  - dusk
  - mysql:8

pipeline:
  - name: Setup
    cmd: |
      cp -v .env.example .env
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate

  - name: Compile Dev Assets
    cmd: |
      npm ci --no-audit
      npm run build
  
  - name: Install extensions
    cmd: |
      printenv
      cat /etc/hosts
      echo "pretend we installed something"
      #wget https://github.com/chipperci/php-extensions/raw/main/8.2/grpc.so
      #wget https://github.com/chipperci/php-extensions/raw/main/8.2/protobuf.so
      #mv *.so /usr/lib/php/20220829/
      #echo "extension=grpc.so" | sudo tee /etc/php/8.2/cli/php.ini
      #echo "extension=protobuf.so" | sudo tee /etc/php/8.2/cli/php.ini
  
  - name: Browser Test
    cmd: | 
      printenv
      mkdir -p /home/chipper/repository/database
      touch /home/chipper/repository/database/database.sqlite
      php -S [::0]:8000 -t public 2>server.log &

      sleep 2

      php artisan dusk:chrome-driver $CHROME_DRIVER
      php artisan dusk --env=testing

  - name: Run Tests
    cmd: phpunit
