# File .chipperci.yml, which goes in the root of your repository
version: 1

environment:
  php: 8.2
  node: 14

services:
  - dusk

pipeline:
  - name: Setup
    cmd: |
      cp -v .env.example .env
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate

  - name: Compile Dev Assets
    cmd: |
      npm ci --no-audit
      npm run build
  
  - name: Browser Test
    cmd: | 
      echo "Dusk Service: $SCV_dusk"
      echo "Dusk host: $DUSK_HOST"
      php -r 'var_dump($_SERVER);'; 
      php -r 'var_dump($_ENV);'; 
      #php -S 0.0.0.0:8000 -t public 2>/dev/null &
      #sleep 1
      #php artisan dusk --env=testing

  - name: Run Tests
    cmd: phpunit
